### PR TITLE
added auth and require auth middleware to components

### PR DESCRIPTION
**Pull request by jessethach**
Client will now talk to the server and retrieve a token. Some routes will still need to require auth.

### CODE REVIEW

**Comment by arialaurel** [comment]
waste-not _gulp_grep_color_1_33_ _120x24

**Comment by jessethach** [comment]
@ltegman proptypes are now declared. Not sure how to fix the if else statement errors and the multi line error. Any tips?

**Comment by arialaurel** [comment]
The else warning is just telling you the else is unneeded. You're returning something if the conditional evaluates to true so the code in the else will never be hit even if it weren't in an else block. Looks like you got all the rest fixed 👍

**Comment by jessethach** [comment]
Gotcha! Thanks – else block removed. PR updated.

**Comment by jessethach** [comment]
closes #41 
Login option will only appear on relevant routes

**Comment by arialaurel** [comment]
Still need to make the navbar button for logout do something, but otherwise this looks solid 👍

**Comment by jessethach** [comment]
Definitely, I might need your help with that. It relates to a localStorage issue that we are also having. I'll make an issue of it.

**Pull request merged**
